local opt = vim.opt
opt.clipboard = ""
opt.number = true
opt.relativenumber = true
opt.expandtab = true
opt.shiftwidth = 4
opt.tabstop = 4
opt.smartindent = true
opt.termguicolors = true
opt.signcolumn = "yes"
opt.mouse = "a"
opt.updatetime = 200
opt.splitright = true
opt.splitbelow = true
