### POSITION ###
position=top-right
offset_x=12
offset_y=12

### LAYOUT ###
table_columns=2
round_corners=6
background_alpha=0.40

### FONT ###
font_size=20

### CORE ###
fps
frametime
frame_timing=1

### GPU ###
gpu_name
vram
gpu_temp
gpu_power

### CPU ###
cpu_mhz
cpu_temp

### RAM ###
ram

### STYLE ###
text_color=FFFFFF

### CLEANUP ###
engine_short_names
