font_family      JetBrainsMono Nerd Font
font_size        12.0
background_opacity 0.85
window_padding_width 10
hide_window_decorations no
confirm_os_window_close 0
enable_audio_bell no
background #2f3638
foreground #e4e9e8

selection_background #596669
selection_foreground #e4e9e8

cursor #a7a1c2
cursor_text_color #2f3638

active_border_color #8d89b6
inactive_border_color #465154

color0  #222728
color8  #596669

color1  #cd7d7d
color9  #d89a9a

color2  #8fa892
color10 #a8c0ab

color3  #b7b08b
color11 #d0c8a1

color4  #7d87a8
color12 #a7a1c2

color5  #8d89b6
color13 #c0bae2

color6  #7ea0a3
color14 #a4c7cb

color7  #e4e9e8
color15 #ffffff
