# Enable colours

set -g default-terminal 'xterm-256color'
set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'

# Prefix key
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Open new windows in current directory path
bind c new-window -c "#{pane_current_path}"

# Split windows
unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind -  split-window -v -c "#{pane_current_path}"

# Reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "⟳ Config reloaded."

# Resize Panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z 

# Enable mouse
set -g mouse on

# Scrollback
set -g history-limit 50000

# VIM Motions
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi "v" send-keys -X begin-selection
bind-key -T copy-mode-vi "y" send-keys -X copy-selection

# Enable Mouse Dragging
unbind -T copy-mode-vi MouseDragEnd1Pane

# Status Line Position
set-option -g status-position top

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm'

 
