# ~/.config/fuzzel/fuzzel.ini

[main]
terminal=kitty --app-id floats
width=40
lines=10
icon-theme=Papirus-Dark

[colors]
background=1e1e2eff
text=cdd6f4ff
match=89b4faff
selection=313244ff
selection-text=cdd6f4ff
border=45475aff

[border]
width=2
radius=8
