# █████╗ ██████╗ ██████╗ ███████╗ █████╗ ██████╗  █████╗ ███╗   ██╗ ██████╗███████╗ 
# ██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔══██╗████╗  ██║██╔════╝██╔════╝     
# ███████║██████╔╝██████╔╝█████╗  ███████║██████╔╝███████║██╔██╗ ██║██║     █████╗     
# ██╔══██║██╔═══╝ ██╔═══╝ ██╔══╝  ██╔══██║██╔══██╗██╔══██║██║╚██╗██║██║     ██╔══╝   
# ██║  ██║██║     ██║     ███████╗██║  ██║██║  ██║██║  ██║██║ ╚████║╚██████╗███████╗   
# ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝╚══════╝  
#-----------------------------------------------------------------------------------

general {
    gaps_in = 2
    gaps_out = 4
    border_size = 2
    col.active_border = rgba(cdd6f4aa)
    col.inactive_border = rgba(595959aa)
    resize_on_border = true
    allow_tearing = false
    layout = dwindle # or master
}

decoration {
    rounding = 4
    active_opacity = 1.0
    inactive_opacity = 1.0
    
    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }
    
    blur {
        enabled = true
        size = 6
        passes = 3
        new_optimizations = true
        ignore_opacity = false
    }
}

# Blur waybar
layerrule = blur on, match:namespace = waybar

# Blur wlogout
layerrule = blur on, match:namespace = logout_dialog

# Blur swaync with alpha handling
layerrule = blur on, ignore_alpha 1, match:namespace = swaync-control-center
layerrule = blur on, ignore_alpha 1, match:namespace = swaync-notification-window
