background {
    path = /tmp/hyprlock.png
    blur_passes = 0
}
input-field {
    size = 300, 50
    outline_thickness = 1

    outer_color = rgba(255,255,255,0.08)
    inner_color = rgba(0,0,0,0.35)

    font_color = rgba(255,255,255,0.85)

    position = 0, -80
    halign = center
    valign = center
}

label {
    text = $TIME
    font_size = 48
    color = rgba(255,255,255,0.85)
    position = 0, 80
    halign = center
    valign = center
}
