################
### MONITORS ###
################
source = ~/.config/hypr/conf/monitors.conf

###################
### ENVIRONMENT ###
###################
source = ~/.config/hypr/conf/environment.conf

###################
### MY PROGRAMS ###
###################
source = ~/.config/hypr/conf/programs.conf

# AUTOSTART 
source = ~/.config/hypr/conf/autostart.conf

#####################
### LOOK AND FEEL ###
#####################
source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/appearance.conf
source = ~/.config/hypr/conf/layout.conf
source = ~/.config/hypr/conf/misc.conf

#############
### INPUT ###
#############
source = ~/.config/hypr/conf/input.conf

###################
### KEYBINDINGS ###
###################
source = ~/.config/hypr/conf/binds.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################
source = ~/.config/hypr/conf/workspaces.conf
source = ~/.config/hypr/conf/windowrules.conf
exec-once= hyprlock

